name: Deploy Frontend to Render

on:
  push:
    branches:
      - deploy/frontend
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
           service-id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
           api-key: ${{ secrets.RENDER_API_KEY }}
           wait-to-success: true
